//
// Created by user_32fji03b on 2022/8/19.
//

#ifndef SUNRISE_FULLSCREENVIDEOADINTERACTIONLISTENER_H
#define SUNRISE_FULLSCREENVIDEOADINTERACTIONLISTENER_H


class FullScreenVideoAdInteractionListener {

};


#endif //SUNRISE_FULLSCREENVIDEOADINTERACTIONLISTENER_H
